spring:
  application:
    name: portfolio-tracker-app

flex:
  query:
    bucket: portfolio_tracker_data
    filename: current/transactions.xml

google:
  sheet:
    id: 1FMoU7vNY4q9Ym20SeWfoonm1RTmKrguAeMNHNB04ROg

server:
  port: ${PORT:8080}



