name: Github Actions Pipeline
on:
  push:
    branches: main

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17.0.10'
          cache: 'maven'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_AUTH_KEY }}'

      - name: Build project
        run: mvn clean install -DskipTests -B

      - name: Run Tests
        run: mvn test -B